[project]
name = "pokemon-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pedro", email = "pedro.h.s.p@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sqlalchemy>=2.1.1",
]

[project.scripts]
pokemon-pipeline = "pokemon_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false